version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
  - package-ecosystem: "github-actions"
    directory: "/"

